import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Starfield from "react-starfield";

// Poprawna deklaracja czcionki
const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Welcome to my porfolio!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} bg-[#04050E] text-white antialiased overflow-y-auto`}
      >
        <Starfield
          starCount={2000}
          starColor={[255, 255, 255]}
          speedFactor={0.012}
          backgroundColor="#04050E"
        />
        {children}
      </body>
    </html>
  );
}
